config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :employees

  devise_for :managers

  root to: "employees#index"
end

app/models/application_record.rb
# frozen_string_literal: true

# app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
# frozen_string_literal: true

# app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :role, presence: true
  validates :salary, presence: true
end

app/models/manager.rb
# frozen_string_literal: true

# app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_manager!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # Allow adding the name attribute using the devise sign_up method
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

# app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[show edit update destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees =
      if params[:search].present?
        Employee.where(
          'lower(name) LIKE ? OR lower(email) LIKE ? OR lower(role) LIKE ?',
          "%#{params[:search].downcase}%",
          "%#{params[:search].downcase}%",
          "%#{params[:search].downcase}%"
        )
      else
        Employee.all
      end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show; end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit; end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        notifier = Slack::Notifier.new ENV['WEBHOOK_URL']
        notifier.ping "Employee #{@employee.name.strip} was successfully created. :memo:"

        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    name = @employee.name

    @employee.destroy

    notifier = Slack::Notifier.new ENV['WEBHOOK_URL']
    notifier.ping "Employee #{name.strip} was successfully destroyed. :wastebasket:"
    
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def employee_params
    params.require(:employee).permit(:name, :email, :role, :salary)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation" class="notification is-danger is-light">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p class="control has-icons-left">
      <%= form.text_field :name, class: "input", placeholder: "Full name" %>
      <span class="icon is-small is-left">
        <i class="fa fa-user"></i>
      </span>
    </p>
  </div>

  <div class="field">
    <p class="control has-icons-left">
      <%= form.text_field :email, class: "input", placeholder: "Email" %>
      <span class="icon is-small is-left">
        <i class="fas fa-envelope"></i>
      </span>
    </p>
  </div>

  <div class="field">
    <p class="control has-icons-left">
      <%= form.text_field :role, class: "input", placeholder: "Role" %>
      <span class="icon is-small is-left">
        <i class="fas fa-briefcase"></i>
      </span>
    </p>
  </div>

  <div class="field">
    <p class="control has-icons-left">
      <%= form.number_field :salary, value: form.object.salary.to_f, step: :any, class: "input", placeholder: "Salary" %>
      <span class="icon is-small is-left">
        <i class="fas fa-money-bill-alt"></i>
      </span>
    </p>
  </div>

  <br/>
  <div class="field">
    <p class="control center">
      <%= form.submit nil, class: 'button is-fullwidth is-rounded is-primary' %>
    </p>
  </div>
<% end %>

app/views/employees/edit.html.erb
<section class="section">
    <div class="container column is-half">
        <h1 class="is-size-3 is-size-4-mobile has-text-centered">Editing Employee</h1>
    </div>

    <div class="container column is-half">
        <%= render 'form', employee: @employee %>
    </div>

    <div class="container column is-one-fifth center">
        <%= link_to 'Show', @employee, class: "button is-fullwidth is-rounded is-outlined is-dark" %> 
    </div>
    <div class="container column is-one-fifth center">
        <%= link_to 'Back', employees_path, class: "button is-fullwidth is-rounded is-outlined is-link" %>
    </div>
</section>

app/views/employees/index.html.erb
<section class="section">
  <% if notice.present? %>
    <div class="notification is-info is-light">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>

  <div class="container column is-half is-mobile">
    <%= form_tag(employees_path, method: :get) do %>
      <div class="columns">
        <div class="column is-four-fifths">
          <%= text_field_tag :search, params[:search], class: "input", placeholder: "Search" %>
        </div>
        <div class="column">
          <%= submit_tag 'Search', name: nil, class: "button is-fullwidth is-rounded is-black" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="container column is-half is-mobile">
    <h1 class="is-size-3 is-size-4-mobile has-text-centered">Employees</h1>
  </div>

  <div class="columns is-mobile">
    <div class="column is-10 is-offset-2">
      <div class="column is-2">
        <%= link_to 'New Employee', new_employee_path, class: "button is-fullwidth is-rounded is-outlined is-primary" %>
      </div>
      <br>

      <div class="table-container">
        <table class="table is-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Role</th>
              <th>Salary</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @employees.each do |employee| %>
              <tr>
                <td><%= employee.name %></td>
                <td><%= employee.email %></td>
                <td><%= employee.role %></td>
                <td><%= number_to_currency(employee.salary, unit: "R$", separator: ",", delimiter: "") %></td>
                <td><%= link_to 'Show', employee, class: "button is-fullwidth is-rounded is-outlined is-info" %></td>
                <td><%= link_to 'Edit', edit_employee_path(employee), class: "button is-fullwidth is-rounded is-outlined is-dark" %></td>
                <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' }, class: "button is-fullwidth is-rounded is-outlined is-danger" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

</section>

app/views/employees/new.html.erb
<section class="section">
    <div class="container column is-half">
        <h1 class="is-size-3 is-size-4-mobile has-text-centered">New Employee</h1>
    </div>

    <div class="container column is-half">
        <%= render 'form', employee: @employee %>
    </div>
    
    <div class="container column is-one-fifth center">
        <%= link_to 'Back', employees_path, class: "button is-fullwidth is-rounded is-outlined is-link" %>
    </div>
</section>

app/views/employees/show.html.erb
<section class="section">
    <% if notice.present? %>
      <div class="notification is-info is-light">
        <p id="notice"><%= notice %></p>
      </div>
    <% end %>

  <div class="container column is-half">
    <h1 class="is-size-2 is-size-1-mobile has-text-centered">
      <%= @employee.name %>
    </h1>
  </div>

  <div class="container column is-half">
    <p class="has-text-centered">
      <strong>Email:</strong> <%= @employee.email %>
    </p>
  </div>

  <div class="container column is-half">
    <p class="has-text-centered">
      <strong>Role:</strong> <%= @employee.role %>
    </p>
  </div>

  <div class="container column is-half">
    <p class="has-text-centered">
      <strong>Salary:</strong> <%= number_to_currency(@employee.salary, unit: "R$", separator: ",", delimiter: "") %>
    </p>
  </div>

  <div class="container column is-one-fifth center">
    <%= link_to 'Edit', edit_employee_path(@employee), class: "button is-fullwidth is-rounded is-outlined is-dark" %> 
  </div>

  <div class="container column is-one-fifth center">
    <%= link_to 'Back', employees_path, class: "button is-fullwidth is-rounded is-outlined is-link" %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <div class='row'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        Employee Manager
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% unless manager_signed_in? %>
              <a class="button is-primary" href='/managers/sign_up'>
                <strong>Sign up</strong>
              </a>
              <a class="button is-light" href='/managers/sign_in'>
                Login 
              </a>
            <% end %>  
            <% if manager_signed_in? %>
              <%= link_to "Logout", destroy_manager_session_path, method: :delete, class: 'button is-light'  %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>